### ISSUE TITLE
Tracking issue

### ISSUE THREAD

**Issue by bgruening** [hash-bash/StudyProject#1]
* create a hand Makefile that:
  * clones/updates the RSE and runs the combine step
  * `make install` should setup everything that you need with conda
  * `make build`
  * `make run` etc should be implemented

get inspiration from https://github.com/galaxyproject/galaxy-hub/blob/master/Makefile#L19

* website, please use a similar style as https://research-software-ecosystem.github.io/

* the merge script should go upstream in a CI task and it should push the combined-file into a special branch, e.g. `combined_metadata`.
* your website should then consume this file from this branch

**Comment by hash-bash** [comment]
Moved the content of this issue to the doc file.
